### ISSUE TITLE
Error: type Polys has no field vtk_id

### ISSUE THREAD

**Issue by Blumenkranz** [JuliaVTK/WriteVTK.jl#155]
Hi, I got an Error when I try to generate polygonal cells. Here's the MWE
```julia
using WriteVTK

vertices = [0.0 0.0;2.0 0.0;0.0 2.0;2.0 2.0;0.0 1.0;2.0 1.0;1.0 0.0;1.0 2.0;1.0 1.0;0.0 0.5;1.0 0.5;0.5 0.0;0.5 1.0;0.5 0.5]'
cells = Vector{MeshCell}(undef,7)
cells[1] = MeshCell(PolyData.Polys(),[1,12,10,14])
cells[2] = MeshCell(PolyData.Polys(),[12,7,14,11])
cells[3] = MeshCell(PolyData.Polys(),[10,14,5,13])
cells[4] = MeshCell(PolyData.Polys(),[14,11,13,9])
cells[5] = MeshCell(PolyData.Polys(),[7,2,9,6,11])
cells[6] = MeshCell(PolyData.Polys(),[5,9,3,8,13])
cells[7] = MeshCell(PolyData.Polys(),[9,6,8,4])
vtk_grid("test_polygon",vertices,cells;append=false) do vtk
    vtk["test",VTKCellData()] = collect(1:7)
end
```

**Comment by jipolanco** [comment]
Hi, this is because `Vector{MeshCell}` is not a concrete type, and WriteVTK dispatches to the wrong function since it cannot guess the exact type of cell.

I'll push a workaround to this issue which will allow to pass a non-concrete container type.

In the meantime, to initialise a vector with the right cell type, you could do something like:

```julia
cells = resize!([MeshCell(PolyData.Polys(),[1,12,10,14])], 7)
```

**Comment by Blumenkranz** [comment]
Thanks for your reply! It helps a lot. And it will be great if non-concrete pass becomes available.
