### ISSUE TITLE
Generalize the package for read/write VTK

### ISSUE THREAD

**Issue by juliohm** [JuliaVTK/WriteVTK.jl#23]
This package is really useful for my research and I wish I could completely forget about other file formats. The problem is that currently I can only save into disk, reading back into Julia is not possible.

Could you consider generalizing this package to a more general VTK.jl package? You definitely have the skills as well as the FileIO.jl generality at your disposal :blush:

**Comment by jipolanco** [comment]
What I don't really have is time. I have some research to do as well, you know? :-)

More seriously, that's definitely a good suggestion and I've thought about it. The VTK file format can vary a lot, but at least I can aim at reading the files that can be generated by WriteVTK.jl. I'll look into it, and I'll also consider integration with FileIO.

**Comment by juliohm** [comment]
I am gonna close this issue since it is already in the plans. Maybe a new package name would be appropriate for handling read/write. I believe that Tim has used the name `VTK.jl` already, but maybe you could use `VTKutils.jl` or something.

**Comment by sebastianpech** [comment]
Is this issue still of interest? I would need the feature and have some time in the next weeks to look into it.

**Comment by jipolanco** [comment]
It would be nice to have. To be honest I probably won't try to implement it myself anytime soon. It can be fairly complex since there's a lot of different ways a VTK file can be written...

Personally in these cases I prefer to work with HDF5 files, since they can be easily written and read back. Data can also be visualised the XDMF format.

So if you're motivated feel free to look into this issue, and I'd be glad to help and merge your code.

**Comment by sebastianpech** [comment]
I'm using BSON files if I really need the data back in julia. My main usage is actually focused on the pvd files in order to append newly generated VTK files (e.g. after restarting a simulation). Would having only this feature be of interest for you, or is that to specific?

**Comment by jipolanco** [comment]
That's actually a great idea. It would definitely be interesting to append stuff to pvd files, and it shouldn't be too difficult to implement.

**Comment by sebastianpech** [comment]
Yep I think so too. I'll start working on it.

**Comment by jipolanco** [comment]
I'm reopening this because it would be good to add reading functionality.

**Comment by sloede** [comment]
Alright, so it finally happened: In https://github.com/trixi-framework/ReadVTK.jl/issues/21, a user came across a workflow where they would like to read in VTK data in Julia, process it, and write it out as VTK again. Therefore, it would be beneficial to be able to reuse the types of WriteVTK.jl, eg, the cell types, also in ReadVTK.jl, to make this a smooth process. 

I see three ways to achieve this:
1. Make WriteVTK.jl a dependency of ReadVTK.jl and use its types directly.
2. Create a VTKBase.jl package that contains common types and make it a dependency for both WriteVTK.jl and ReadVTK.jl
3. Merge WriteVTK.jl and ReadVTK.jl into a single package under a new name (VTK.jl?)

Variant 1) would require the least effort on the parts of the WriteVTK.jl developers, but it would IMHO also be the least elegant solution. Variant 3) OTOH would be the nicest in terms of user convenience, but also incur the most maintainer overhead, especially since Interfaces and code would probably have to be refactored quite extensively. Thus my current favorite would be to investigate how much effort/trouble variant 2) would mean and, if deemed acceptable, try to use this approach. 

What do you think, @jipolanco? 

cc @ranocha @Matthew-Whisenant

**Comment by jipolanco** [comment]
> Thus my current favorite would be to investigate how much effort/trouble variant 2) would mean and, if deemed acceptable, try to use this approach.

@sloede I completely agree with you. Option 2 is easily doable and the maintenance burden should be minimal. Option 3 would be nice, but unless someone is willing to do the work, I don't think it will happen in the short term.

I'll create a VTKBase.jl package and move some definitions there, including cell types.

**Comment by jipolanco** [comment]
@sloede So I moved cell types and most `struct` definitions to a new [VTKBase.jl](https://github.com/jipolanco/VTKBase.jl) package, which is now being registered. I will add you as a collaborator in case you need to add further definitions for ReadVTK.jl. Feel free to add other contributors.

What I still need to figure out is what to do about the documentation. Some of the types moved to VTKBase.jl have docstrings, and until now they have appeared in the WriteVTK.jl docs. I think it would be great to keep it this way (maybe providing a clearer distinction between VTKBase and WriteVTK definitions in the docs, and even including ReadVTK if that makes sense to you), but I'm not very familiar with combining docs from different packages. I believe you do something similar in Trixi?

**Comment by sloede** [comment]
> So I moved cell types and most `struct` definitions to a new [VTKBase.jl](https://github.com/jipolanco/VTKBase.jl) package, which is now being registered.

Great, thanks for creating VTKBase.jl! I just submitted two PRs for TagBot and CompatHelper.

> I will add you as a collaborator in case you need to add further definitions for ReadVTK.jl. Feel free to add other contributors.

Since it's a repo in a personal account, I actually do not have access to any of the settings. But since I expect this to be a low maintenance repo once properly set up, I think it's all good for now 🙂 

> What I still need to figure out is what to do about the documentation. Some of the types moved to VTKBase.jl have docstrings, and until now they have appeared in the WriteVTK.jl docs. I think it would be great to keep it this way (maybe providing a clearer distinction between VTKBase and WriteVTK definitions in the docs, and even including ReadVTK if that makes sense to you), but I'm not very familiar with combining docs from different packages. I believe you do something similar in Trixi?

Regarding documentation I propose that we just add a section to the types in VTKBase.jl in each downstream repo WriteVTK.jl and ReadVTK.jl. It's a little redundant, but the most user friendly. Once set up, it is also minimal maintenance (we did this with Trixi2Vtk.jl, where the docs are available in Trixi.jl, see e.g. https://github.com/trixi-framework/Trixi.jl/blob/main/docs/make.jl). Should this not work well for users (or us), we can always reconsider.

**Comment by jipolanco** [comment]
> Regarding documentation I propose that we just add a section to the types in VTKBase.jl in each downstream repo WriteVTK.jl and ReadVTK.jl. It's a little redundant, but the most user friendly. Once set up, it is also minimal maintenance (we did this with Trixi2Vtk.jl, where the docs are available in Trixi.jl, see e.g. https://github.com/trixi-framework/Trixi.jl/blob/main/docs/make.jl). Should this not work well for users (or us), we can always reconsider.

Sounds good to me! Thanks, the Trixi.jl example is very helpful, I see that it's quite easy to combine documentation from multiple packages.

**Comment by ranocha** [comment]
Great, thanks a lot!

**Comment by juliohm** [comment]
Given the existence of ReadVTK.jl and WriteVTK.jl, this issue can now be closed.
